apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vprodb
  name: vprodb
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: vprodb
status:
  loadBalancer: {}
