apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vpromc
  name: vpromc
spec:
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    app: vpromc
status:
  loadBalancer: {}
