apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vprodb
  name: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vprodb
    spec:
      containers:
      - image: web927/vprofiledb:V1
        name: vprofiledb
        args:
          - "ignore-db-dir=lost+found"
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: vpro-db-data
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-sceret
                key: db-pass
      volumes:
        - name: vpro-db-data
          gcePersistentDisk:
            pdName: my-data-disk
            fsType: ext4